"""Load `.kicad_mod` footprint files into pipeline Footprint models.

Parses S-expression `.kicad_mod` files (as generated by easyeda2kicad or
KiCad's standard libraries) into the pipeline's :class:`Footprint` dataclass.
This avoids parametric footprint generation for ICs with verified JLCPCB
footprints — eliminating pad-alignment errors.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from kicad_pipeline.models.pcb import (
    Footprint,
    FootprintArc,
    FootprintCircle,
    FootprintLine,
    FootprintText,
    Pad,
    Point,
)
from kicad_pipeline.sexp.parser import parse

if TYPE_CHECKING:
    from pathlib import Path

_log = logging.getLogger(__name__)

# Type alias for parsed S-expression nodes
_SNode = int | float | str | bool | list["_SNode"]


def _to_float(val: _SNode) -> float:
    """Coerce an S-expression atom to float.

    Handles int, float, str, and bool. Lists raise ValueError.
    """
    if isinstance(val, bool):
        return 1.0 if val else 0.0
    if isinstance(val, int | float):
        return float(val)
    if isinstance(val, str):
        return float(val)
    msg = f"Cannot convert list to float: {val!r}"
    raise ValueError(msg)


def _find_nodes(tree: list[_SNode], tag: str) -> list[list[_SNode]]:
    """Find all child lists whose first element matches *tag*."""
    return [
        child
        for child in tree
        if isinstance(child, list) and len(child) > 0 and child[0] == tag
    ]


def _find_node(tree: list[_SNode], tag: str) -> list[_SNode] | None:
    """Find first child list whose first element matches *tag*."""
    nodes = _find_nodes(tree, tag)
    return nodes[0] if nodes else None


def _get_value(node: list[_SNode], tag: str) -> _SNode | None:
    """Get the second element of the first child matching *tag*."""
    child = _find_node(node, tag)
    if child is not None and len(child) > 1:
        return child[1]
    return None


def _parse_at(node: list[_SNode]) -> tuple[float, float, float]:
    """Parse ``(at X Y [ROT])`` → ``(x, y, rotation)``."""
    at = _find_node(node, "at")
    if at is None:
        return (0.0, 0.0, 0.0)
    x = _to_float(at[1]) if len(at) > 1 else 0.0
    y = _to_float(at[2]) if len(at) > 2 else 0.0
    rot = _to_float(at[3]) if len(at) > 3 else 0.0
    return (x, y, rot)


def _parse_size(node: list[_SNode]) -> tuple[float, float]:
    """Parse ``(size W H)`` → ``(w, h)``."""
    size = _find_node(node, "size")
    if size is None:
        return (0.0, 0.0)
    return (_to_float(size[1]), _to_float(size[2]))


def _parse_layers(node: list[_SNode]) -> tuple[str, ...]:
    """Parse ``(layers L1 L2 ...)`` → tuple of layer names."""
    layers = _find_node(node, "layers")
    if layers is None:
        return ()
    return tuple(str(layer) for layer in layers[1:])


def _parse_layer(node: list[_SNode]) -> str:
    """Parse ``(layer NAME)`` → layer name string."""
    layer_node = _find_node(node, "layer")
    if layer_node is not None and len(layer_node) > 1:
        return str(layer_node[1])
    # Fallback: second element of the node itself might be the layer
    return "F.Cu"


def _parse_width(node: list[_SNode]) -> float:
    """Parse ``(width W)`` → float."""
    width = _get_value(node, "width")
    if width is not None:
        return _to_float(width)
    # KiCad 9+ uses (stroke (width W) ...) instead
    stroke = _find_node(node, "stroke")
    if stroke is not None:
        sw = _get_value(stroke, "width")
        if sw is not None:
            return _to_float(sw)
    return 0.12


def _parse_pad(pad_node: list[_SNode]) -> Pad:
    """Parse a ``(pad ...)`` S-expression node into a :class:`Pad`."""
    # (pad NUM TYPE SHAPE (at X Y ROT) (size W H) (layers ...) [(drill D)])
    number = str(pad_node[1]) if len(pad_node) > 1 else ""
    pad_type_raw = str(pad_node[2]) if len(pad_node) > 2 else "smd"
    shape = str(pad_node[3]) if len(pad_node) > 3 else "rect"

    # Normalize pad type
    pad_type_map = {
        "smd": "smd",
        "thru_hole": "thru_hole",
        "np_thru_hole": "np_thru_hole",
        "connect": "smd",
    }
    pad_type = pad_type_map.get(pad_type_raw, pad_type_raw)

    x, y, _rot = _parse_at(pad_node)
    size_w, size_h = _parse_size(pad_node)
    layers = _parse_layers(pad_node)

    # Drill
    drill_node = _find_node(pad_node, "drill")
    drill: float | None = None
    if drill_node is not None and len(drill_node) > 1:
        # Handle (drill <size>) and (drill oval <w> <h>) forms
        try:
            drill = _to_float(drill_node[1])
        except (ValueError, TypeError):
            # e.g. (drill oval 0.6 1.0) — use first numeric value
            for elem in drill_node[2:]:
                try:
                    drill = _to_float(elem)
                    break
                except (ValueError, TypeError):
                    continue

    # Roundrect ratio
    rr_node = _find_node(pad_node, "roundrect_rratio")
    rr_ratio: float | None = None
    if rr_node is not None and len(rr_node) > 1:
        rr_ratio = _to_float(rr_node[1])

    return Pad(
        number=number,
        pad_type=pad_type,
        shape=shape,
        position=Point(x=x, y=y),
        size_x=size_w,
        size_y=size_h,
        layers=layers,
        drill_diameter=drill,
        roundrect_ratio=rr_ratio,
    )


def _parse_fp_line(node: list[_SNode]) -> FootprintLine | None:
    """Parse ``(fp_line (start X Y) (end X Y) (layer L) (width W))``."""
    start = _find_node(node, "start")
    end = _find_node(node, "end")
    if start is None or end is None:
        return None
    layer = _parse_layer(node)
    width = _parse_width(node)
    return FootprintLine(
        start=Point(x=_to_float(start[1]), y=_to_float(start[2])),
        end=Point(x=_to_float(end[1]), y=_to_float(end[2])),
        layer=layer,
        width=width,
    )


def _parse_fp_circle(node: list[_SNode]) -> FootprintCircle | None:
    """Parse ``(fp_circle (center X Y) (end X Y) (layer L) (width W))``."""
    center = _find_node(node, "center")
    end = _find_node(node, "end")
    if center is None or end is None:
        return None
    layer = _parse_layer(node)
    width = _parse_width(node)
    return FootprintCircle(
        center=Point(x=_to_float(center[1]), y=_to_float(center[2])),
        end=Point(x=_to_float(end[1]), y=_to_float(end[2])),
        layer=layer,
        width=width,
    )


def _parse_fp_arc(node: list[_SNode]) -> FootprintArc | None:
    """Parse ``(fp_arc (start X Y) (mid X Y) (end X Y) (layer L) (width W))``."""
    start = _find_node(node, "start")
    mid = _find_node(node, "mid")
    end = _find_node(node, "end")
    if start is None or end is None:
        return None
    layer = _parse_layer(node)
    width = _parse_width(node)
    # easyeda2kicad may not emit mid — use start as fallback
    if mid is None:
        mid = start
    return FootprintArc(
        start=Point(x=_to_float(start[1]), y=_to_float(start[2])),
        mid=Point(x=_to_float(mid[1]), y=_to_float(mid[2])),
        end=Point(x=_to_float(end[1]), y=_to_float(end[2])),
        layer=layer,
        width=width,
    )


def _parse_fp_text(node: list[_SNode], text_type: str) -> FootprintText | None:
    """Parse ``(fp_text TYPE TEXT (at X Y) (layer L) (effects ...))``."""
    if len(node) < 3:
        return None
    text = str(node[2])
    x, y, rot = _parse_at(node)
    layer = _parse_layer(node)
    # Check hidden
    hidden = any(el == "hide" for el in node if isinstance(el, str))
    # Effects size
    effects = _find_node(node, "effects")
    size = 1.0
    if effects is not None:
        font = _find_node(effects, "font")
        if font is not None:
            font_size = _find_node(font, "size")
            if font_size is not None and len(font_size) > 1:
                size = _to_float(font_size[1])
    return FootprintText(
        text_type=text_type,
        text=text,
        position=Point(x=x, y=y),
        layer=layer,
        rotation=rot,
        effects_size=size,
        hidden=hidden,
    )


def load_kicad_mod(
    path: Path,
    ref: str,
    value: str,
    layer: str = "F.Cu",
    lcsc: str | None = None,
) -> Footprint:
    """Parse a ``.kicad_mod`` file into a pipeline :class:`Footprint`.

    Handles both easyeda2kicad format (``module`` keyword) and KiCad 9+
    format (``footprint`` keyword).

    Args:
        path: Path to the ``.kicad_mod`` file.
        ref: Reference designator (e.g. ``"U3"``).
        value: Component value string (e.g. ``"ESP32-S3-WROOM-1"``).
        layer: Placement layer (default ``"F.Cu"``).
        lcsc: Optional LCSC part number.

    Returns:
        Fully constructed :class:`Footprint` with all pads and graphics.

    Raises:
        FileNotFoundError: If *path* does not exist.
        ValueError: If the file cannot be parsed as a valid footprint.
    """
    text = path.read_text(encoding="utf-8")
    tree = parse(text)

    if not isinstance(tree, list) or len(tree) < 2:
        msg = f"Invalid .kicad_mod structure in {path}"
        raise ValueError(msg)

    # Root tag is either "module" (easyeda2kicad / KiCad 7) or "footprint" (KiCad 9+)
    root_tag = tree[0]
    if root_tag not in ("module", "footprint"):
        msg = f"Expected 'module' or 'footprint' root, got {root_tag!r} in {path}"
        raise ValueError(msg)

    # lib_id from module/footprint name
    lib_name = str(tree[1]) if len(tree) > 1 else "unknown"
    lib_id = lib_name if ":" in lib_name else f"jlcpcb:{lib_name}"

    # Detect attr (smd / through_hole)
    attr_node = _find_node(tree, "attr")
    attr = "smd"
    if attr_node is not None and len(attr_node) > 1:
        attr = str(attr_node[1])
        if attr == "through_hole":
            attr = "through_hole"

    # Parse pads
    pads: list[Pad] = []
    for pad_node in _find_nodes(tree, "pad"):
        pads.append(_parse_pad(pad_node))

    # Parse graphics
    graphics: list[FootprintLine | FootprintArc | FootprintCircle] = []
    for line_node in _find_nodes(tree, "fp_line"):
        line = _parse_fp_line(line_node)
        if line is not None:
            graphics.append(line)
    for circle_node in _find_nodes(tree, "fp_circle"):
        circle = _parse_fp_circle(circle_node)
        if circle is not None:
            graphics.append(circle)
    for arc_node in _find_nodes(tree, "fp_arc"):
        arc = _parse_fp_arc(arc_node)
        if arc is not None:
            graphics.append(arc)

    # Parse texts
    texts: list[FootprintText] = []
    for text_node in _find_nodes(tree, "fp_text"):
        if len(text_node) > 1:
            text_type_raw = str(text_node[1])
            text_type_map = {
                "reference": "reference",
                "value": "value",
                "user": "user",
            }
            text_type = text_type_map.get(text_type_raw, "user")
            ft = _parse_fp_text(text_node, text_type)
            if ft is not None:
                # Override reference/value text with caller-provided values
                if text_type == "reference":
                    ft = FootprintText(
                        text_type="reference",
                        text=ref,
                        position=ft.position,
                        layer=ft.layer,
                        rotation=ft.rotation,
                        effects_size=ft.effects_size,
                        hidden=ft.hidden,
                    )
                elif text_type == "value":
                    ft = FootprintText(
                        text_type="value",
                        text=value,
                        position=ft.position,
                        layer=ft.layer,
                        rotation=ft.rotation,
                        effects_size=ft.effects_size,
                        hidden=ft.hidden,
                    )
                texts.append(ft)

    _log.info(
        "Loaded .kicad_mod: %s → %d pads, %d graphics, %d texts",
        path.name, len(pads), len(graphics), len(texts),
    )

    return Footprint(
        lib_id=lib_id,
        ref=ref,
        value=value,
        position=Point(x=0.0, y=0.0),
        rotation=0.0,
        layer=layer,
        pads=tuple(pads),
        graphics=tuple(graphics),
        texts=tuple(texts),
        lcsc=lcsc,
        attr=attr,
    )
